project_id = "pmxnfpnnvtuuiedoxuxc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge-runtime]
enabled = true
port = 54327

[functions.image-proxy]
verify_jwt = false

[functions.storage-manager]
verify_jwt = true

[functions.secure-coin-actions]
verify_jwt = true

[functions.send-custom-emails]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.confirm-email-and-redirect]
verify_jwt = false

[functions.admin-auto-login]
verify_jwt = false