-- Fix the view_product_with_tags view to remove faulty column references
-- First drop the existing view if it exists
DROP VIEW IF EXISTS public.view_product_with_tags;

-- Recreate the view with proper column names (no idasproduct_id references)
CREATE VIEW public.view_product_with_tags AS
SELECT 
  p.id as product_id,
  p.name as product_name,
  p.description as product_description,
  p.price as product_price,
  p.pro_price,
  p.list_price,
  p.new_price,
  p.digital_price,
  p.discount_price,
  p.image as product_image,
  p.additional_images,
  p.sizes,
  p.colors,
  p.stock as product_stock,
  p.badge_text,
  p.badge_color,
  p.badge_visible,
  p.specifications,
  p.technical_specs,
  p.product_features,
  p.shipping_weight,
  p.free_shipping,
  p.meta_title,
  p.meta_description,
  p.slug,
  p.is_active,
  p.is_featured,
  p.brand,
  p.category,
  p.platform,
  p.condition,
  p.promotional_price,
  p.discount_percentage,
  p.pix_discount_percentage,
  p.uti_pro_price,
  p.installment_options,
  p.rating_average,
  p.rating_count,
  p.pro_discount_percent,
  p.uti_pro_enabled,
  p.uti_pro_value,
  p.uti_pro_custom_price,
  p.uti_pro_type,
  p.parent_product_id,
  p.is_master_product,
  p.product_type,
  p.sku_code,
  p.variant_attributes,
  p.sort_order,
  p.available_variants,
  p.master_slug,
  p.inherit_from_master,
  p.product_videos,
  p.product_faqs,
  p.product_highlights,
  p.reviews_config,
  p.trust_indicators,
  p.manual_related_products,
  p.breadcrumb_config,
  p.product_descriptions,
  p.delivery_config,
  p.display_config,
  p.created_at,
  p.updated_at,
  t.id as tag_id,
  t.name as tag_name
FROM public.products p
LEFT JOIN public.product_tags pt ON p.id = pt.product_id
LEFT JOIN public.tags t ON pt.tag_id = t.id;

-- Grant SELECT permission to all users
GRANT SELECT ON public.view_product_with_tags TO anon, authenticated;